# Generated by Django 4.2.1 on 2023-06-16 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='NameGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Название игры',
                'verbose_name_plural': 'Названия игр',
            },
        ),
        migrations.CreateModel(
            name='KeyGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.TextField(max_length=30, verbose_name='Ключ')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.namegame', verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Ключ игры',
                'verbose_name_plural': 'Ключи игр',
                'ordering': ['name'],
            },
        ),
    ]
