# Generated by Django 4.2.1 on 2023-06-16 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_product_name'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='product',
            index_together=set(),
        ),
        migrations.AddField(
            model_name='product',
            name='connect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.namegame', verbose_name='Связь с игрой'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.TextField(verbose_name='Название игры'),
        ),
        migrations.AlterIndexTogether(
            name='product',
            index_together={('name', 'slug')},
        ),
    ]
