# Generated by Django 4.2.1 on 2023-06-16 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_namegame_alter_order_created_alter_order_paid_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KeyGame',
        ),
        migrations.DeleteModel(
            name='NameGame',
        ),
    ]
